version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
  - when: pull_request.*
    validate:
      - do: size
        ignore: ['README.md', 'ignore_this_directory/*', '**/test*.py']
        lines:
          max:
            count: 10
            message: Change is very large. Should be under 10 lines of addtions and deletions.
